# Generated by Django 3.2.9 on 2021-12-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_businesspartner_accountholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slot_connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.slots'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_partner', to='app.businesspartner'),
        ),
        migrations.AlterField(
            model_name='slots',
            name='wingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.wing'),
        ),
    ]
