# Generated by Django 3.2.9 on 2022-02-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211214_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date_auto']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paymentDate']},
        ),
    ]
