# Generated by Django 3.2.9 on 2022-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_table_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_data',
            name='table_data',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
