# Generated by Django 3.2.8 on 2022-05-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_table_data_table_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=120)),
                ('make', models.CharField(max_length=120)),
                ('model', models.IntegerField()),
                ('carRegistrationState', models.CharField(max_length=120)),
                ('color', models.EmailField(max_length=254)),
                ('insurance', models.CharField(max_length=120)),
                ('permitYear', models.CharField(max_length=120)),
                ('bookingId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_link', to='app.booking')),
            ],
        ),
    ]
