# Generated by Django 3.2.9 on 2022-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date_auto']},
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='mobileNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
