# Generated by Django 3.2.9 on 2022-10-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220603_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Status',
            field=models.CharField(default='failed', max_length=100),
        ),
    ]
