# Generated by Django 3.2.9 on 2022-10-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='key',
            field=models.CharField(default='fai-led', max_length=100),
        ),
    ]
