# Generated by Django 3.2.9 on 2022-10-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_payment_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=120)),
                ('make', models.CharField(max_length=120)),
                ('model', models.IntegerField()),
                ('carRegistrationState', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('insurance', models.CharField(max_length=120)),
                ('permitYear', models.CharField(max_length=120)),
                ('bookingId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.CharField(max_length=120)),
                ('date_auto', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(max_length=120)),
                ('startFrom', models.CharField(max_length=120)),
                ('endTo', models.CharField(max_length=120)),
                ('slotid', models.CharField(max_length=120)),
                ('plan', models.CharField(max_length=120)),
                ('charge', models.CharField(max_length=120)),
                ('slot_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slots')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.businesspartner')),
            ],
            options={
                'ordering': ['-date_auto'],
            },
        ),
    ]
