# Generated by Django 3.2.9 on 2022-10-04 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_bookingtemp_carinfotemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfotemp',
            name='bookingId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.bookingtemp'),
        ),
    ]
