# Generated by Django 3.2.9 on 2022-10-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_carinfotemp_bookingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
                ('transNum', models.CharField(max_length=120, null=True)),
                ('serviceType', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
